server:
  ssl:
    key-store: "classpath:keystore/keystore.jks"
    key-store-password: "password"
  port: 8999

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: "postgres"

  jpa:
    hibernate:
      ddl-auto: "create"